__title__ = 'naturalcolors'
__version__ = '1.0.0'
__license__ = 'MIT'
__author__ = 'Fabio D. Steffen'
__email__ = 'fabio.steffen@chem.uzh.ch'
__description__ = 'Nature color palette'
__keywords__ = 'colormap, colors, nature'
__url__ = 'https://github.com/fdsteffen/naturalcolors'
__copyright__ = '2019 {}'.format(__author__)
